name: S3 Code Backup
on:
  schedule:
    - cron:  '* */12 * * *'    # At every 12th hour
env:
  FOLDER: charts
  BUCKET: hybird-code-backups
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Create a folder in S3
        run: |
          aws s3api put-object --bucket ${{env.BUCKET}} --key ${{env.FOLDER}}/${{env.NOW}}/  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'

      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          MIRROR_TARGET: ${{env.BUCKET}}/${{env.FOLDER}}/${{env.NOW}}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: --overwrite --remove
